### ISSUE TITLE
Meccanismo di sparo

### ISSUE THREAD

**Issue by NicolaPasquali** [NicolaPasquali/offline-game#4]
DIPENDE DALLA ISSUE #5 
Il gioco è uno sparatutto, per cui sarebbe bello se l'utente potesse sparare...
I proiettili devono interagire con i punti vita dei bersagli.

**Comment by ghost** [comment]
Possiamo ispirarci a questo: [https://medium.com/web-maker/making-asteroids-with-kontra-js-and-web-maker-95559d39b45f](https://medium.com/web-maker/making-asteroids-with-kontra-js-and-web-maker-95559d39b45f)

**Comment by NicolaPasquali** [comment]
Ok, buona idea! Da valutare cosa conviene tra la gestione della rotazione e la [gestione del click](https://straker.github.io/kontra/api/pointer#onDown)
