### ISSUE TITLE
Creare immagini per i nemici

### ISSUE THREAD

**Issue by ghost** [NicolaPasquali/offline-game#8]
Seguire questo: https://www.youtube.com/watch?v=wOSX65F96iw

**Comment by NicolaPasquali** [comment]
Ti riscrivo qua la lista di assets:

- 1 sprite per il bug
- 1 sprite per gli improvements
- 3 sprite di persone (colleghi e stakeholders)
- 2 sprite per i loghi (Facebook e YouTube)

**Comment by ghost** [comment]
Ho creato intanto uno sprite con i loghi (Fb, youtube, email), le 3 persone e un goblin che sarebbe il bug (forse cambiamo colore?)
Le persone hanno 2 posizioni, come se camminassero (possiamo farle andare il loop).

Lo sprite è unico, con "campi" di 16 x 16px

Peso totale: 1.2 kB!
In fondo al file ho già preventivato una fila di immagini in più per quando decidiamo lo sfondo.

**Comment by NicolaPasquali** [comment]
Non usando più Kontra dovremmo gestire noi a mano l'animazione, per cui sono sufficienti anche delle immagini statiche (stile Dragon Quest).
